// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlA5VJY48j4Frv11o-P82KDWepkJlqa_c',
    appId: '1:927517323812:web:5cf7861a187582e57b1eb1',
    messagingSenderId: '927517323812',
    projectId: 'teleject-dd58b',
    authDomain: 'teleject-dd58b.firebaseapp.com',
    storageBucket: 'teleject-dd58b.appspot.com',
    measurementId: 'G-8TXG5HHF2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDa7rsHMo9Ag4acvqHSUlge5sVi68bUUs',
    appId: '1:927517323812:android:aa9fb0f217339cef7b1eb1',
    messagingSenderId: '927517323812',
    projectId: 'teleject-dd58b',
    storageBucket: 'teleject-dd58b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVwH5v9lIFWSlQoKovYaCcfF8F1og_0fY',
    appId: '1:927517323812:ios:141e0c9ac115c9297b1eb1',
    messagingSenderId: '927517323812',
    projectId: 'teleject-dd58b',
    storageBucket: 'teleject-dd58b.appspot.com',
    androidClientId: '927517323812-tm0i1ueo5pifo666jq65nh1hubgs25as.apps.googleusercontent.com',
    iosClientId: '927517323812-acpbns8o6cnqic9lgpgimr36nfv3jpqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.teleject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVwH5v9lIFWSlQoKovYaCcfF8F1og_0fY',
    appId: '1:927517323812:ios:141e0c9ac115c9297b1eb1',
    messagingSenderId: '927517323812',
    projectId: 'teleject-dd58b',
    storageBucket: 'teleject-dd58b.appspot.com',
    androidClientId: '927517323812-tm0i1ueo5pifo666jq65nh1hubgs25as.apps.googleusercontent.com',
    iosClientId: '927517323812-acpbns8o6cnqic9lgpgimr36nfv3jpqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.teleject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlA5VJY48j4Frv11o-P82KDWepkJlqa_c',
    appId: '1:927517323812:web:e3b60fe153478e587b1eb1',
    messagingSenderId: '927517323812',
    projectId: 'teleject-dd58b',
    authDomain: 'teleject-dd58b.firebaseapp.com',
    storageBucket: 'teleject-dd58b.appspot.com',
    measurementId: 'G-VSB34XN8P8',
  );
}
